baseurl = "http://melies-hugo.js.org"
publishDir = "docs"
languageCode = "es"
title = "Blog proyecto Méliès"
theme = "hucore"
copyright = "&copy; 2017 Cristina Fernández | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥ | <a href=\"https://js.org\" target=\"_blank\" title=\"JS.ORG | JavaScript Community\"><img src=\"https://logo.js.org/dark_tiny.png\" width=\"77\" alt=\"JS.ORG Logo\"></a>"
disqusShortname = "ilusionismo-con-github-pages"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Illusionismo con GitHub Pages"
keywords = ["GitHub Pages", "Front-end", "Georges Méliès"]
author = "Cristina Fernández"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/cristinafsanz"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/cristinafsanz"
fa_icon = "fa-twitter"
